# Generated by Django 5.0 on 2024-01-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='smscounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_sms', models.IntegerField(default=0)),
                ('remaining_sms', models.IntegerField(default=0)),
            ],
        ),
    ]
