# Generated by Django 5.0 on 2024-01-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_smscounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='sms_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
