# Generated by Django 5.0 on 2024-01-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_sms_count_smscount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='smscount',
            new_name='sms_count',
        ),
    ]
